#ifndef S21_CONSTANTS_H
#define S21_CONSTANTS_H

#define BG_BOARD_ROWS_COUNT 20
#define BG_BOARD_COLUMNS_COUNT 10

#define BG_TETROMINO_SIZE 4
#define BG_TETROMINOS_COUNT 7

#define BG_LEVEL_STEP_FALL_SPEED 1
#define BG_DEFAULT_FALL_TIME_MS 1070
#define BG_SPEED_STEP_TIME_MS 70

#endif
