#ifndef S21_CLI_CONSTANTS_H
#define S21_CLI_CONSTANTS_H

#define CLI_GAME_INFO_WIN_ROWS_COUNT 20
#define CLI_GAME_INFO_WIN_COLUMN_COUNT 10

#define CLI_WIN_BORDER_SIZE_X 1
#define CLI_WIN_BORDER_SIZE_Y 1

#define CLI_VIEW_CHAR_SIZE_X 2
#define CLI_VIEW_CHAR_SIZE_Y 1

#define CLI_Empty ACS_BULLET
#define CLI_Full ACS_CKBOARD

#endif