#ifndef S21_TETRIS_CONSTANTS_H
#define S21_TETRIS_CONSTANTS_H

#define TTRS_TETROMINO_SPAWN_POS_X \
  ((BG_BOARD_COLUMNS_COUNT / 2) - (BG_TETROMINO_SIZE / 2))
#define TTRS_TETROMINO_SPAWN_POS_Y -2

#define TTRS_LEVEL_SCORE_STEP 600
#define TTRS_MAX_LEVEL 10

#endif