/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/_unittests.check" instead.
 */

#include <check.h>
#include <stdio.h>

#include "s21_matrix.h"
#include "s21_utils.h"

START_TEST(calc_complements1) {
  // Checking unit matrix
  const int rows = rand() % 100 + 1;
  matrix_t test = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, rows, &test);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < rows; j++) {
      test.matrix[i][j] = 0;
    }
    test.matrix[i][i] = 1;
  }
  ck_assert_int_eq(s21_calc_complements(&test, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&test, &check), SUCCESS);
  s21_remove_matrix(&test);
  s21_remove_matrix(&check);
}
END_TEST

START_TEST(calc_complements2) {
  // Checking matrix in the task
  matrix_t test = {0};
  matrix_t check = {0};
  matrix_t total = {0};
  s21_create_matrix(3, 3, &test);
  s21_create_matrix(3, 3, &total);
  test.matrix[0][0] = 1;
  test.matrix[0][1] = 2;
  test.matrix[0][2] = 3;
  test.matrix[1][0] = 0;
  test.matrix[1][1] = 4;
  test.matrix[1][2] = 2;
  test.matrix[2][0] = 5;
  test.matrix[2][1] = 2;
  test.matrix[2][2] = 1;
  total.matrix[0][0] = 0;
  total.matrix[0][1] = 10;
  total.matrix[0][2] = -20;
  total.matrix[1][0] = 4;
  total.matrix[1][1] = -14;
  total.matrix[1][2] = 8;
  total.matrix[2][0] = -8;
  total.matrix[2][1] = -2;
  total.matrix[2][2] = 4;
  ck_assert_int_eq(s21_calc_complements(&test, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(calc_complements3) {
  // Result matrix is NULL
  const int rows = rand() % 100 + 1;
  matrix_t test = {0};
  s21_create_matrix(rows, rows, &test);
  ck_assert_int_eq(s21_calc_complements(&test, NULL), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(calc_complements4) {
  // Set matrix is NULL
  matrix_t check = {0};
  ck_assert_int_eq(s21_calc_complements(NULL, &check), ERROR);
}
END_TEST

START_TEST(calc_complements5) {
  // The matrix isn't square
  const int rows = 4;
  const int columns = 5;
  matrix_t test = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, columns, &test);
  ck_assert_int_eq(s21_calc_complements(&test, &check), CALC_ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(calc_complements6) {
  // Checking random matrix
  matrix_t test = {0};
  matrix_t check = {0};
  matrix_t total = {0};
  s21_create_matrix(3, 3, &test);
  s21_create_matrix(3, 3, &total);
  test.matrix[0][0] = 8.32;
  test.matrix[0][1] = 0.01;
  test.matrix[0][2] = 12;
  test.matrix[1][0] = 5;
  test.matrix[1][1] = -1.12;
  test.matrix[1][2] = 7;
  test.matrix[2][0] = 22;
  test.matrix[2][1] = -9.89;
  test.matrix[2][2] = 1;
  total.matrix[0][0] = 68.11;
  total.matrix[0][1] = 149;
  total.matrix[0][2] = -24.81;
  total.matrix[1][0] = -118.69;
  total.matrix[1][1] = -255.68;
  total.matrix[1][2] = 82.5048;
  total.matrix[2][0] = 13.51;
  total.matrix[2][1] = 1.76;
  total.matrix[2][2] = -9.3684;
  ck_assert_int_eq(s21_calc_complements(&test, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(create_matrix1) {
  // Checking the number of rows, columns, internal values and total result with
  // null values and remove function
  int rows = rand() % 100 + 1;
  int columns = rand() % 100 + 1;
  matrix_t test = {0};
  ck_assert_int_eq(s21_create_matrix(rows, columns, &test), OK);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      ck_assert_int_eq(0, test.matrix[i][j]);
    }
  }
  ck_assert_int_eq(test.rows, rows);
  ck_assert_int_eq(test.columns, columns);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(create_matrix2) {
  // The number of rows is null
  int rows = 0;
  int columns = rand() % 100 + 1;
  matrix_t test = {0};
  ck_assert_int_eq(s21_create_matrix(rows, columns, &test), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(create_matrix3) {
  // The number of columns is null
  int rows = rand() % 100 + 1;
  int columns = 0;
  matrix_t test = {0};
  ck_assert_int_eq(s21_create_matrix(rows, columns, &test), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(create_matrix4) {
  // Passing NULL
  int rows = rand() % 100 + 1;
  int columns = rand() % 100 + 1;
  ck_assert_int_eq(s21_create_matrix(rows, columns, NULL), ERROR);
}
END_TEST

START_TEST(determinant1) {
  // Checking matrix with same number in rows and columns
  const int rows = rand() % 100 + 1;
  matrix_t test = {0};
  double check = 0;
  double total = 0;
  s21_create_matrix(rows, rows, &test);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < rows; j++) {
      test.matrix[i][j] = 1;
    }
  }
  ck_assert_int_eq(s21_determinant(&test, &check), OK);
  ck_assert_double_eq_tol(total, check, FRACTURE_CHECK);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(determinant2) {
  // Check unit matrix
  const int rows = rand() % 100 + 1;
  matrix_t test = {0};
  double check = 0;
  double total = 1;
  s21_create_matrix(rows, rows, &test);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < rows; j++) {
      test.matrix[i][j] = 0;
      test.matrix[i][i] = 1;
    }
  }
  ck_assert_int_eq(s21_determinant(&test, &check), OK);
  ck_assert_double_eq_tol(total, check, FRACTURE_CHECK);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(determinant3) {
  // Check random matrix
  const int rows = 4;
  matrix_t test = {0};
  double check = 0;
  double total = 16654.35;
  s21_create_matrix(rows, rows, &test);
  test.matrix[0][0] = 4.5;
  test.matrix[0][1] = 3;
  test.matrix[0][2] = 32;
  test.matrix[0][3] = 11;
  test.matrix[1][0] = 0.1;
  test.matrix[1][1] = 3;
  test.matrix[1][2] = -5;
  test.matrix[1][3] = 12;
  test.matrix[2][0] = 1;
  test.matrix[2][1] = 8.9;
  test.matrix[2][2] = 4;
  test.matrix[2][3] = 7;
  test.matrix[3][0] = -5;
  test.matrix[3][1] = 3;
  test.matrix[3][2] = 2;
  test.matrix[3][3] = 1;
  ck_assert_int_eq(s21_determinant(&test, &check), OK);
  ck_assert_double_eq_tol(total, check, FRACTURE_CHECK);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(determinant4) {
  // Result is NULL
  const int rows = rand() % 100 + 1;
  matrix_t test = {0};
  s21_create_matrix(rows, rows, &test);
  ck_assert_int_eq(s21_determinant(&test, NULL), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(determinant5) {
  // Set matrix is NULL
  double check = 0;
  ck_assert_int_eq(s21_determinant(NULL, &check), ERROR);
}
END_TEST

START_TEST(determinant6) {
  // The matrix isn't square
  const int rows = 4;
  const int columns = 5;
  matrix_t test = {0};
  double check = 0;
  s21_create_matrix(rows, columns, &test);
  ck_assert_int_eq(s21_determinant(&test, &check), CALC_ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(determinant7) {
  // Check matrix reduction
  matrix_t test = {0};
  matrix_t total = {0};
  matrix_t check = {0};
  s21_create_matrix(4, 4, &test);
  s21_create_matrix(3, 3, &total);
  int num = 1;
  for (int i = 0; i < 4; i++) {
    for (int j = 0; j < 4; j++) {
      test.matrix[i][j] = num;
      num += 1;
    }
  }
  total.matrix[0][0] = 6;
  total.matrix[0][1] = 7;
  total.matrix[0][2] = 8;
  total.matrix[1][0] = 10;
  total.matrix[1][1] = 11;
  total.matrix[1][2] = 12;
  total.matrix[2][0] = 14;
  total.matrix[2][1] = 15;
  total.matrix[2][2] = 16;
  matrix_reduction(&test, &check, 0, 0);
  ck_assert_int_eq(s21_eq_matrix(&check, &total), SUCCESS);
  s21_remove_matrix(&test);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(eq_matrix1) {
  // Checking equal matrix
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  s21_create_matrix(rows, columns, &test1);
  s21_create_matrix(rows, columns, &test2);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      double random = get_rand(DBL_MIN, DBL_MAX);
      test1.matrix[i][j] = random;
      test2.matrix[i][j] = random;
    }
  }
  ck_assert_int_eq(s21_eq_matrix(&test1, &test2), SUCCESS);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
}
END_TEST

START_TEST(eq_matrix2) {
  // The number of rows of each matrix is 0
  const int rows = 0;
  const int columns = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  s21_create_matrix(rows, columns, &test1);
  s21_create_matrix(rows, columns, &test2);
  ck_assert_int_eq(s21_eq_matrix(&test1, &test2), FAILURE);
}
END_TEST

START_TEST(eq_matrix3) {
  // The number of rows is different
  const int rows1 = 5;
  const int rows2 = 6;
  const int columns = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  s21_create_matrix(rows1, columns, &test1);
  s21_create_matrix(rows2, columns, &test2);
  for (int i = 0; i < rows2; i++) {
    for (int j = 0; j < columns; j++) {
      double random = get_rand(DBL_MIN, DBL_MAX);
      if (i != 5) test1.matrix[i][j] = random;
      test2.matrix[i][j] = random;
    }
  }
  ck_assert_int_eq(s21_eq_matrix(&test1, &test2), FAILURE);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
}
END_TEST

START_TEST(eq_matrix4) {
  // The number of columns is different
  const int rows = rand() % 100 + 1;
  const int columns1 = 5;
  const int columns2 = 6;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  s21_create_matrix(rows, columns1, &test1);
  s21_create_matrix(rows, columns2, &test2);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns2; j++) {
      double random = get_rand(DBL_MIN, DBL_MAX);
      if (j != 5) test1.matrix[i][j] = random;
      test2.matrix[i][j] = random;
    }
  }
  ck_assert_int_eq(s21_eq_matrix(&test1, &test2), FAILURE);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
}
END_TEST

START_TEST(eq_matrix5) {
  // Both matrices are NULL
  ck_assert_int_eq(s21_eq_matrix(NULL, NULL), FAILURE);
}
END_TEST

START_TEST(eq_matrix6) {
  // One number in second matrix is different
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  s21_create_matrix(rows, columns, &test1);
  s21_create_matrix(rows, columns, &test2);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      double random = get_rand(DBL_MIN, DBL_MAX);
      test1.matrix[i][j] = random;
      test2.matrix[i][j] = random;
      if (i == (rows - 1) && j == (columns - 1)) {
        test1.matrix[i][j] = 0.000005;
        test2.matrix[i][j] = 0.000007;
      }
    }
  }
  ck_assert_int_eq(s21_eq_matrix(&test1, &test2), FAILURE);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
}
END_TEST

START_TEST(inverse_matrix1) {
  // Checking unit matrix
  const int rows = rand() % 100 + 1;
  matrix_t test = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, rows, &test);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < rows; j++) {
      test.matrix[i][j] = 0;
    }
    test.matrix[i][i] = 1;
  }
  ck_assert_int_eq(s21_inverse_matrix(&test, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&test, &check), SUCCESS);
  s21_remove_matrix(&test);
  s21_remove_matrix(&check);
}
END_TEST

START_TEST(inverse_matrix2) {
  // Checking matrix in the task
  matrix_t test = {0};
  matrix_t check = {0};
  matrix_t total = {0};
  s21_create_matrix(3, 3, &test);
  s21_create_matrix(3, 3, &total);
  test.matrix[0][0] = 2;
  test.matrix[0][1] = 5;
  test.matrix[0][2] = 7;
  test.matrix[1][0] = 6;
  test.matrix[1][1] = 3;
  test.matrix[1][2] = 4;
  test.matrix[2][0] = 5;
  test.matrix[2][1] = -2;
  test.matrix[2][2] = -3;
  total.matrix[0][0] = 1;
  total.matrix[0][1] = -1;
  total.matrix[0][2] = 1;
  total.matrix[1][0] = -38;
  total.matrix[1][1] = 41;
  total.matrix[1][2] = -34;
  total.matrix[2][0] = 27;
  total.matrix[2][1] = -29;
  total.matrix[2][2] = 24;
  ck_assert_int_eq(s21_inverse_matrix(&test, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(inverse_matrix3) {
  // Result matrix is NULL
  const int rows = rand() % 100 + 1;
  matrix_t test = {0};
  s21_create_matrix(rows, rows, &test);
  ck_assert_int_eq(s21_inverse_matrix(&test, NULL), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(inverse_matrix4) {
  // Set matrix is NULL
  matrix_t check = {0};
  ck_assert_int_eq(s21_inverse_matrix(NULL, &check), ERROR);
}
END_TEST

START_TEST(inverse_matrix5) {
  // The matrix isn't square
  const int rows = 4;
  const int columns = 5;
  matrix_t test = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, columns, &test);
  ck_assert_int_eq(s21_inverse_matrix(&test, &check), CALC_ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(inverse_matrix6) {
  // Checking random matrix
  matrix_t test = {0};
  matrix_t check = {0};
  matrix_t total = {0};
  s21_create_matrix(3, 3, &test);
  s21_create_matrix(3, 3, &total);
  test.matrix[0][0] = 1;
  test.matrix[0][1] = 2;
  test.matrix[0][2] = 2;
  test.matrix[1][0] = 4;
  test.matrix[1][1] = 4;
  test.matrix[1][2] = 6;
  test.matrix[2][0] = 7;
  test.matrix[2][1] = 8;
  test.matrix[2][2] = 9;
  total.matrix[0][0] = -1.5;
  total.matrix[0][1] = -0.25;
  total.matrix[0][2] = 0.5;
  total.matrix[1][0] = 0.75;
  total.matrix[1][1] = -0.625;
  total.matrix[1][2] = 0.25;
  total.matrix[2][0] = 0.5;
  total.matrix[2][1] = 0.75;
  total.matrix[2][2] = -0.5;
  ck_assert_int_eq(s21_inverse_matrix(&test, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(inverse_matrix7) {
  // The determinant is null
  const int rows = rand() % 100 + 1;
  matrix_t test = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, rows, &test);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < rows; j++) {
      test.matrix[i][j] = 0;
    }
  }
  ck_assert_int_eq(s21_inverse_matrix(&test, &check), CALC_ERROR);
  s21_remove_matrix(&test);
  s21_remove_matrix(&check);
}
END_TEST

START_TEST(mult_matrix1) {
  // Checking mult of equal matrix with nulls
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  const int commonNum = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  matrix_t check = {0};
  matrix_t total = {0};
  s21_create_matrix(rows, commonNum, &test1);
  s21_create_matrix(commonNum, columns, &test2);
  s21_create_matrix(rows, columns, &total);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      total.matrix[i][j] = 0;
    }
  }
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < commonNum; j++) {
      test1.matrix[i][j] = 0;
    }
  }
  for (int i = 0; i < commonNum; i++) {
    for (int j = 0; j < columns; j++) {
      test2.matrix[i][j] = 0;
    }
  }
  ck_assert_int_eq(s21_mult_matrix(&test1, &test2, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(mult_matrix2) {
  // Checking an example with simple numbers
  const int rows = 2;
  const int columns = 3;
  int num = 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  matrix_t check = {0};
  matrix_t total = {0};
  s21_create_matrix(rows, columns, &test1);
  s21_create_matrix(columns, rows, &test2);
  s21_create_matrix(rows, rows, &total);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      test1.matrix[i][j] = num;
      test2.matrix[j][i] = -num;
      num += 1;
    }
  }
  total.matrix[0][0] = -14;
  total.matrix[0][1] = -32;
  total.matrix[1][0] = -32;
  total.matrix[1][1] = -77;
  ck_assert_int_eq(s21_mult_matrix(&test1, &test2, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(mult_matrix3) {
  // Checking an example with complex numbers
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  matrix_t check = {0};
  matrix_t total = {0};
  s21_create_matrix(rows, columns, &test1);
  s21_create_matrix(columns, rows, &test2);
  s21_create_matrix(rows, rows, &total);
  for (int i = 0; i < rows; i++)
    for (int j = 0; j < columns; j++)
      test1.matrix[i][j] = get_rand(-10e10, 10e10);
  for (int i = 0; i < columns; i++)
    for (int j = 0; j < rows; j++) test2.matrix[i][j] = get_rand(-10e10, 10e10);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < rows; j++) {
      total.matrix[i][j] = 0;
      for (int k = 0; k < columns; k++)
        total.matrix[i][j] += test1.matrix[i][k] * test2.matrix[k][j];
    }
  }
  ck_assert_int_eq(s21_mult_matrix(&test1, &test2, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(mult_matrix4) {
  // The multiplication condition is not fulfilled
  const int rows = 11;
  const int columns = 12;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, columns, &test1);
  s21_create_matrix(rows, columns, &test2);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      double num = get_rand(DBL_MIN, DBL_MAX);
      test1.matrix[i][j] = num;
      test2.matrix[i][j] = num;
    }
  }
  ck_assert_int_eq(s21_mult_matrix(&test1, &test2, &check), CALC_ERROR);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
}
END_TEST

START_TEST(mult_matrix5) {
  // Result matrix is NULL
  const int rows = rand() % 100 + 1;
  matrix_t test = {0};
  s21_create_matrix(rows, rows, &test);
  ck_assert_int_eq(s21_mult_matrix(&test, &test, NULL), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(mult_matrix6) {
  // Set matrix is NULL
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, columns, &test);
  ck_assert_int_eq(s21_mult_matrix(&test, NULL, &check), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(mult_number1) {
  // Checking mult of matrix with null
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  double num = 0;
  matrix_t test = {0};
  matrix_t total = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, columns, &test);
  s21_create_matrix(rows, columns, &total);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      test.matrix[i][j] = get_rand(DBL_MIN, DBL_MAX);
      total.matrix[i][j] = 0;
    }
  }
  ck_assert_int_eq(s21_mult_number(&test, num, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test);
  s21_remove_matrix(&total);
  s21_remove_matrix(&check);
}
END_TEST

START_TEST(mult_number2) {
  // Random number subtraction
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  double num = get_rand(DBL_MIN, DBL_MAX);
  matrix_t test = {0};
  matrix_t check = {0};
  matrix_t total = {0};
  s21_create_matrix(rows, columns, &test);
  s21_create_matrix(rows, columns, &total);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      double randomNum = get_rand(DBL_MIN, DBL_MAX);
      test.matrix[i][j] = randomNum;
      total.matrix[i][j] = num * randomNum;
    }
  }
  ck_assert_int_eq(s21_mult_number(&test, num, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(mult_number3) {
  // Result matrix is NULL
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  double num = get_rand(DBL_MIN, DBL_MAX);
  matrix_t test = {0};
  s21_create_matrix(rows, columns, &test);
  ck_assert_int_eq(s21_mult_number(&test, num, NULL), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(mult_number4) {
  // Set matrix is NULL
  double num = get_rand(DBL_MIN, DBL_MAX);
  matrix_t check = {0};
  ck_assert_int_eq(s21_mult_number(NULL, num, &check), ERROR);
}
END_TEST

START_TEST(sub_matrix1) {
  // Checking sub of equal matrix with nulls
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, columns, &test1);
  s21_create_matrix(rows, columns, &test2);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      test1.matrix[i][j] = 0;
      test2.matrix[i][j] = 0;
    }
  }
  ck_assert_int_eq(s21_sub_matrix(&test1, &test2, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&test1, &check), SUCCESS);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
  s21_remove_matrix(&check);
}
END_TEST

START_TEST(sub_matrix2) {
  // Random number subtraction
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  matrix_t check = {0};
  matrix_t total = {0};
  s21_create_matrix(rows, columns, &test1);
  s21_create_matrix(rows, columns, &test2);
  s21_create_matrix(rows, columns, &total);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      double firstNum = get_rand(DBL_MIN, DBL_MAX);
      double secondNum = get_rand(DBL_MIN, DBL_MAX);
      test1.matrix[i][j] = firstNum;
      test2.matrix[i][j] = secondNum;
      total.matrix[i][j] = firstNum - secondNum;
    }
  }
  ck_assert_int_eq(s21_sub_matrix(&test1, &test2, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(sub_matrix3) {
  // Matrices have different number of rows
  const int rows1 = 11;
  const int rows2 = 12;
  const int columns = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  matrix_t check = {0};
  s21_create_matrix(rows1, columns, &test1);
  s21_create_matrix(rows2, columns, &test2);
  for (int i = 0; i < rows2; i++) {
    for (int j = 0; j < columns; j++) {
      double num = get_rand(DBL_MIN, DBL_MAX);
      if (i != rows2 - 1) test1.matrix[i][j] = num;
      test2.matrix[i][j] = num;
    }
  }
  ck_assert_int_eq(s21_sub_matrix(&test1, &test2, &check), CALC_ERROR);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
}
END_TEST

START_TEST(sub_matrix4) {
  // Result matrix is NULL
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test = {0};
  s21_create_matrix(rows, columns, &test);
  ck_assert_int_eq(s21_sub_matrix(&test, &test, NULL), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(sub_matrix5) {
  // Set matrix is NULL
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, columns, &test);
  ck_assert_int_eq(s21_sub_matrix(&test, NULL, &check), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(sum_matrix1) {
  // Checking sum of equal matrix with nulls
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, columns, &test1);
  s21_create_matrix(rows, columns, &test2);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      test1.matrix[i][j] = 0;
      test2.matrix[i][j] = 0;
    }
  }
  ck_assert_int_eq(s21_sum_matrix(&test1, &test2, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&test1, &check), SUCCESS);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
  s21_remove_matrix(&check);
}
END_TEST

START_TEST(sum_matrix2) {
  // Random number addition
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  matrix_t check = {0};
  matrix_t total = {0};
  s21_create_matrix(rows, columns, &test1);
  s21_create_matrix(rows, columns, &test2);
  s21_create_matrix(rows, columns, &total);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      double firstNum = get_rand(DBL_MIN, DBL_MAX);
      double secondNum = get_rand(DBL_MIN, DBL_MAX);
      test1.matrix[i][j] = firstNum;
      test2.matrix[i][j] = secondNum;
      total.matrix[i][j] = firstNum + secondNum;
    }
  }
  ck_assert_int_eq(s21_sum_matrix(&test1, &test2, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(sum_matrix3) {
  // Matrices have different number of rows
  const int rows1 = 11;
  const int rows2 = 12;
  const int columns = rand() % 100 + 1;
  matrix_t test1 = {0};
  matrix_t test2 = {0};
  matrix_t check = {0};
  s21_create_matrix(rows1, columns, &test1);
  s21_create_matrix(rows2, columns, &test2);
  for (int i = 0; i < rows2; i++) {
    for (int j = 0; j < columns; j++) {
      double num = get_rand(DBL_MIN, DBL_MAX);
      if (i != rows2 - 1) test1.matrix[i][j] = num;
      test2.matrix[i][j] = num;
    }
  }
  ck_assert_int_eq(s21_sum_matrix(&test1, &test2, &check), CALC_ERROR);
  s21_remove_matrix(&test1);
  s21_remove_matrix(&test2);
}
END_TEST

START_TEST(sum_matrix4) {
  // Result matrix is NULL
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test = {0};
  s21_create_matrix(rows, columns, &test);
  ck_assert_int_eq(s21_sum_matrix(&test, &test, NULL), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(sum_matrix5) {
  // Set matrix is NULL
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, columns, &test);
  ck_assert_int_eq(s21_sum_matrix(&test, NULL, &check), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(transpose1) {
  // Checking matrix with same number
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test = {0};
  matrix_t total = {0};
  matrix_t check = {0};
  s21_create_matrix(rows, columns, &test);
  s21_create_matrix(columns, rows, &total);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      test.matrix[i][j] = 1;
      total.matrix[j][i] = 1;
    }
  }
  ck_assert_int_eq(s21_transpose(&test, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test);
  s21_remove_matrix(&total);
  s21_remove_matrix(&check);
}
END_TEST

START_TEST(transpose2) {
  // Random number subtraction
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test = {0};
  matrix_t check = {0};
  matrix_t total = {0};
  s21_create_matrix(rows, columns, &test);
  s21_create_matrix(columns, rows, &total);
  for (int i = 0; i < rows; i++) {
    for (int j = 0; j < columns; j++) {
      double randomNum = get_rand(DBL_MIN, DBL_MAX);
      test.matrix[i][j] = randomNum;
      total.matrix[j][i] = randomNum;
    }
  }
  ck_assert_int_eq(s21_transpose(&test, &check), OK);
  ck_assert_int_eq(s21_eq_matrix(&total, &check), SUCCESS);
  s21_remove_matrix(&test);
  s21_remove_matrix(&check);
  s21_remove_matrix(&total);
}
END_TEST

START_TEST(transpose3) {
  // Result matrix is NULL
  const int rows = rand() % 100 + 1;
  const int columns = rand() % 100 + 1;
  matrix_t test = {0};
  s21_create_matrix(rows, columns, &test);
  ck_assert_int_eq(s21_transpose(&test, NULL), ERROR);
  s21_remove_matrix(&test);
}
END_TEST

START_TEST(transpose4) {
  // Set matrix is NULL
  matrix_t check = {0};
  ck_assert_int_eq(s21_transpose(NULL, &check), ERROR);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("calc_complements");
  TCase *tc1_1 = tcase_create("calc_complements");
  Suite *s2 = suite_create("create_matrix");
  TCase *tc2_1 = tcase_create("create_matrix");
  Suite *s3 = suite_create("determinant");
  TCase *tc3_1 = tcase_create("determinant");
  Suite *s4 = suite_create("eq_matrix");
  TCase *tc4_1 = tcase_create("eq_matrix");
  Suite *s5 = suite_create("inverse_matrix");
  TCase *tc5_1 = tcase_create("inverse_matrix");
  Suite *s6 = suite_create("mult_matrix");
  TCase *tc6_1 = tcase_create("mult_matrix");
  Suite *s7 = suite_create("mult_number");
  TCase *tc7_1 = tcase_create("mult_number");
  Suite *s8 = suite_create("sub_matrix");
  TCase *tc8_1 = tcase_create("sub_matrix");
  Suite *s9 = suite_create("sum_matrix");
  TCase *tc9_1 = tcase_create("sum_matrix");
  Suite *s10 = suite_create("transpose");
  TCase *tc10_1 = tcase_create("transpose");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, calc_complements1);
  tcase_add_test(tc1_1, calc_complements2);
  tcase_add_test(tc1_1, calc_complements3);
  tcase_add_test(tc1_1, calc_complements4);
  tcase_add_test(tc1_1, calc_complements5);
  tcase_add_test(tc1_1, calc_complements6);
  suite_add_tcase(s2, tc2_1);
  tcase_add_test(tc2_1, create_matrix1);
  tcase_add_test(tc2_1, create_matrix2);
  tcase_add_test(tc2_1, create_matrix3);
  tcase_add_test(tc2_1, create_matrix4);
  suite_add_tcase(s3, tc3_1);
  tcase_add_test(tc3_1, determinant1);
  tcase_add_test(tc3_1, determinant2);
  tcase_add_test(tc3_1, determinant3);
  tcase_add_test(tc3_1, determinant4);
  tcase_add_test(tc3_1, determinant5);
  tcase_add_test(tc3_1, determinant6);
  tcase_add_test(tc3_1, determinant7);
  suite_add_tcase(s4, tc4_1);
  tcase_add_test(tc4_1, eq_matrix1);
  tcase_add_test(tc4_1, eq_matrix2);
  tcase_add_test(tc4_1, eq_matrix3);
  tcase_add_test(tc4_1, eq_matrix4);
  tcase_add_test(tc4_1, eq_matrix5);
  tcase_add_test(tc4_1, eq_matrix6);
  suite_add_tcase(s5, tc5_1);
  tcase_add_test(tc5_1, inverse_matrix1);
  tcase_add_test(tc5_1, inverse_matrix2);
  tcase_add_test(tc5_1, inverse_matrix3);
  tcase_add_test(tc5_1, inverse_matrix4);
  tcase_add_test(tc5_1, inverse_matrix5);
  tcase_add_test(tc5_1, inverse_matrix6);
  tcase_add_test(tc5_1, inverse_matrix7);
  suite_add_tcase(s6, tc6_1);
  tcase_add_test(tc6_1, mult_matrix1);
  tcase_add_test(tc6_1, mult_matrix2);
  tcase_add_test(tc6_1, mult_matrix3);
  tcase_add_test(tc6_1, mult_matrix4);
  tcase_add_test(tc6_1, mult_matrix5);
  tcase_add_test(tc6_1, mult_matrix6);
  suite_add_tcase(s7, tc7_1);
  tcase_add_test(tc7_1, mult_number1);
  tcase_add_test(tc7_1, mult_number2);
  tcase_add_test(tc7_1, mult_number3);
  tcase_add_test(tc7_1, mult_number4);
  suite_add_tcase(s8, tc8_1);
  tcase_add_test(tc8_1, sub_matrix1);
  tcase_add_test(tc8_1, sub_matrix2);
  tcase_add_test(tc8_1, sub_matrix3);
  tcase_add_test(tc8_1, sub_matrix4);
  tcase_add_test(tc8_1, sub_matrix5);
  suite_add_tcase(s9, tc9_1);
  tcase_add_test(tc9_1, sum_matrix1);
  tcase_add_test(tc9_1, sum_matrix2);
  tcase_add_test(tc9_1, sum_matrix3);
  tcase_add_test(tc9_1, sum_matrix4);
  tcase_add_test(tc9_1, sum_matrix5);
  suite_add_tcase(s10, tc10_1);
  tcase_add_test(tc10_1, transpose1);
  tcase_add_test(tc10_1, transpose2);
  tcase_add_test(tc10_1, transpose3);
  tcase_add_test(tc10_1, transpose4);

  srunner_add_suite(sr, s2);
  srunner_add_suite(sr, s3);
  srunner_add_suite(sr, s4);
  srunner_add_suite(sr, s5);
  srunner_add_suite(sr, s6);
  srunner_add_suite(sr, s7);
  srunner_add_suite(sr, s8);
  srunner_add_suite(sr, s9);
  srunner_add_suite(sr, s10);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
